version: '3.6'

services:
  flare:
    image: soulteary/flare
    restart: always
    # 默认无需添加任何参数，如有特殊需求
    # 可阅读文档 https://github.com/soulteary/docker-flare/blob/main/docs/advanced-startup.md
    command: flare --disable_login=0 --visibility=private
    environment:
      # 开启登陆
      - FLARE_DISABLE_LOGIN=0
      # 设置登陆账号
      - FLARE_USER=flare
      # 指定你自己的账号密码，如未设置 `FLARE_USER`，则会默认生成密码并展示在应用启动日志中
      - FLARE_PASS=your_password
    ports:
      # 根据自己需求设置端口，如需调整访问端口为 8080，
      # 可参考修改为 `- 8080:5005`
      - 5005:5005
    volumes:
      - ./app:/app
